name: Laravel Deployment
concurrency: production_environment

on:
  workflow_call:
    inputs:
      php-version:
        description: "PHP version"
        required: false
        default: "8.3"
        type: string
      deploy-namespace:
        description: "Deploy Namespace"
        required: false
        default: ${{ github.ref_name }}
        type: string
    # Read here why secrets should be passed by caller workflow. Resuable workflow don't have direct access to secrets.
    # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
    # > Workflows that call reusable workflows in the same organization or enterprise can use the inherit keyword to implicitly pass the secrets.
    secrets:
      PRIVATE_KEY:
        description: "Private key for deployment"
        required: true

jobs:
  deploy-laravel-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ inputs.php-version }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Deploy
        uses: deployphp/action@master
        env:
          SECRET_PATH: ${{ env.SECRET_PATH }}
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy ${{ inputs.deploy-namespace }}
          verbosity: -vvv
